language: node_js
node_js:
- node

after_success:
- npm version patch
- git add .
- git commit -m 'bump patch version'
- git push origin master

deploy:
  provider: npm
  email: vince.lugli@gmail.com
  api_key: $NPM_KEY
  skip_cleanup: true
  on:
    repo: music-markdown/markdown-it-music
    branch: master
