language: node_js
node_js:
  - node
deploy:
  - provider: script
    script: git checkout master
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: npm version patch -m "Bump version %s [skip ci]"
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: git push https://$GITHUB_TOKEN@github.com/music-markdown/markdown-it-music.git master
    skip_cleanup: true
    on:
      branch: master
  - provider: npm
    email: vince.lugli@gmail.com
    api_key: $NPM_KEY
    skip_cleanup: true
    on:
      repo: music-markdown/markdown-it-music
      branch: master
